#!/bin/bash

set -e

_main() {
  local BDT="${1:-nightly}"
  local APP="${3:-SideBackup}"
  local OUT="build.xcarchive/Products/Applications/$APP.app"
  local SDR="build.xcarchive/dSYMs"
  local SYM="$APP.app.dSYM"
  local BVR=$(grep 'MARKETING' Build.xcconfig | awk '{ print $3 }')
  local GS=$(git rev-parse --short HEAD)
  if [[ -n "$2" ]]; then
    local GB=$(echo "$2" | sed 's/\//_/g')
  else
    local GB=$(git branch --show-current | sed 's/\//_/g')
  fi
  local BARGS="archive\
 -scheme $APP\
 -archivePath build.xcarchive\
 -destination generic/platform=iOS"
  if [[ "$BDT" == "release" ]]; then
    local VER="$BVR"
    local ARGS="$BARGS"
  else
    local VER="$(date +'%y%m%d%H%M')+$BVR+$GB+$GS"
    local ARGS="$BARGS MARKETING_VERSION=$VER"
  fi
  local OPA="build/$APP.$VER.ipa"

  _mkipa() {
    p=Payload
    mkdir $p
    mv "${1%.*}.app" $p
    zip -qr9 "${1%.*}.ipa" $p
    rm -r $p
  }

  [[ -d "build" ]] && rm -r build || true && mkdir build
  [[ -f "build.xcarchive" ]] && rm -r build.xcarchive
  echo "::group::Build $BDT"
  echo "[$VER] Building.."
  NSUnbufferedIO=YES set -o pipefail && xcodebuild $ARGS 2>&1 | tee "build/$VER.log" | xcbeautify --renderer github-actions
  echo "[$VER] Archiving.."
  xz -e "build/$VER.log"
  _mkipa "$OUT"
  tar cf "build/$SYM.$VER.tar" -C "$SDR" "$SYM"
  xz -e "build/$SYM.$VER.tar"
  mv "${OUT%.*}.ipa" "$OPA"
  rm -r build.xcarchive
  #tar cvJf "build.$VER.tar.xz" build
  echo "[$VER] Done!"
  echo "::endgroup::"
}

_main "$@"
