#!/bin/bash

set -e

_main() {
  _mkipa() {
    p=Payload
    mkdir $p
    mv "$1.app" $p
    zip -qr9 "$1.ipa" $p
    rm -r $p
  }

  local BUILD_TYPE="${1:-nightly}"
  if [[ -n "$GITHUB_REF" ]]; then
    if [[ "$GITHUB_REF" = ref/tags/* ]]; then
      local BUILD_TYPE="release"
    fi
    local COMMIT="$GITHUB_SHA"
    local BRANCH="${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}"
  else
    local COMMIT="$(git rev-parse HEAD)"
    local BRANCH=$(git branch --show-current)
  fi
  COMMIT="${COMMIT:0:8}"
  BRANCH="$(echo $BRANCH | sed 's/\//_/g')"
  local APP="${2:-$(basename *xcodeproj .xcodeproj)}"
  local XCARCHIVE="${XCARCHIVE:-$APP.xcarchive}"
  local BUILDOUT="$XCARCHIVE/Products/Applications/$APP"
  local DSYM="$APP.app.dSYM"
  local VER="$(grep 'MARKETING' Build.xcconfig | awk '{ print $3 }')"
  local ARGS="archive -scheme $APP -archivePath $XCARCHIVE -destination generic/platform=iOS"
  if [[ "$BUILD_TYPE" = nightly ]]; then
    VER="$(date +'%y%m%d%H%M')+$VER+$BRANCH+$COMMIT"
    ARGS="$ARGS MARKETING_VERSION=$VER"
  fi
  local LOG="build/$VER.log"
  local OUTIPA="build/$APP.$VER.ipa"
  local DSYMTAR="build/$DSYM.$VER.tar"

  [[ -d "build" ]] && rm -r build || true && mkdir build
  [[ -d "$XCARCHIVE" ]] && rm -r $XCARCHIVE
  echo "::group:: Building $BUILD_TYPE"
  echo "[$VER] Building.."
  NSUnbufferedIO=YES set -o pipefail && xcodebuild $ARGS 2>&1 | tee "$LOG" | xcbeautify --renderer github-actions
  echo "[$VER] Archiving.."
  xz -e "$LOG"
  tar cf "$DSYMTAR" -C "$XCARCHIVE/dSYMs" "$DSYM"
  xz -e "$DSYMTAR"
  _mkipa "$BUILDOUT"
  mv "$BUILDOUT.ipa" "$OUTIPA"
  rm -r "$XCARCHIVE"
  if [[ -n "$GITHUB_SHA" ]]; then
    echo "log=$(basename $LOG.xz)" >> $GITHUB_OUTPUT
    echo "sym=$(basename $DSYMTAR.xz)" >> $GITHUB_OUTPUT
    echo "ipa=$(basename $OUTIPA)" >> $GITHUB_OUTPUT
  fi
  echo "[$VER] Done!"
  echo "::endgroup::"
}

_main "$@"
